#!/bin/bash

#We create the directory for it
mkdir -p pokemon_data

DIR="pokemon_data"

#Save the list of names to the variable
pokemons=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")

echo "Starting the parallel data..."

for p in "${pokemons[@]}"; do
	{
	echo "fetching data for $p..."
	response=$(curl -s -w"%{http_code}" -o "$DIR/$p.json" "https://pokeapi.co/api/v2/pokemon/$p")

	if ["$response" -eq 200 ]; then
		echo "saved the data to $DIR/$p.json"
	else
		echo "failed to fetch data for $p with status code $response" >> error_log.txt
		echo "skipping $p."
	fi
	#to avoid hitting the API rate limits
	sleep 2

	}&
done

wait
echo "Data fetching completed."
