#!/bin/bash

#Extracting data to variable
name=$(jq -r '.name' data.json)
height=$(jq -r '.height' data.json)
weight=$(jq -r '.weight' data.json)
type=$(jq -r '.types[0].type.name' data.json)

#Adjusting the units 
formatted_height=$(awk "BEGIN {print $height/10}")
formatted_weight=$(awk "BEGIN {print $weight/10}")

#Output
echo "$(echo $name | sed 's/.*/\u&/') is of type $(echo $type | sed 's/.*/\u&/'), weighs ${formatted_weight}kg, and is ${formatted_height}m tall."