#!/bin/bash

#Well specify where the datas are stored
DATA_DIR="pokemon_data"

#Report to be created
REPORT_FILE="pokemon_report.csv"

echo "CSV Report generated at: $REPORT_FILE"

#Creating the CSV header
echo "Name,Height (m),Weight (kg)" > "$REPORT_FILE"

#Well loop through all the json files
for file in "$DATA_DIR"/*.json; do
	name=$(jq -r '.name' "$file")
	height=$(jq -r '.height' "$file")
	weight=$(jq -r '.weight' "$file")

	height_m=$(awk "BEGIN {print $height/10}")
	weight_kg=$(awk "BEGIN {print $weight/10}")

	name_cap=$(echo "$name" | sed 's/.*/\u&/')

	echo "$name_cap,$height_m,$weight_kg" >> "$REPORT_FILE"
done

echo
cat "$REPORT_FILE"

#Calculating and Printing the average height and weight
awk -F',' 'NR>1 {height+=$2; weight+=$3; count++} 
END {
  printf "\nAverage Height: %.2f m\nAverage Weight: %.2f kg\n", height/count, weight/count
}' "$REPORT_FILE"